2020-02-18 14:17:24,716 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]

2020-02-18 14:17:38,818 ERROR: Exception on /edit_profile [POST] [in d:\flask\my_project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\flask\my_project\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\flask\my_project\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\flask\my_project\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\flask\my_project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "d:\flask\my_project\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\flask\my_project\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\flask\my_project\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Flask\my_project\app\routes.py", line 97, in edit_profile
    db.session.commit()
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1036, in commit
    self.transaction.commit()
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\session.py", line 503, in commit
    self._prepare_impl()
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\session.py", line 482, in _prepare_impl
    self.session.flush()
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2479, in flush
    self._flush(objects)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2617, in _flush
    transaction.rollback(_capture_exception=True)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2577, in _flush
    flush_context.execute()
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 422, in execute
    rec.execute(self)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 589, in execute
    uow,
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 236, in save_obj
    update,
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\engine\base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "d:\flask\my_project\venv\lib\site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('diko', 'I am Python developer!!!\r\nI like React!', 4)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2020-02-18 14:40:35,604 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 16:19:59,719 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 16:20:17,639 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 16:20:44,456 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 16:22:35,373 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 16:34:14,746 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 16:37:34,697 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 19:30:08,600 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 19:33:54,679 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-18 21:06:39,185 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:46]
2020-02-19 16:47:59,040 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:48]
2020-02-19 16:51:03,466 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:48]
2020-04-16 10:06:59,030 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:53]
2020-04-16 10:55:45,850 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
2020-04-16 11:23:27,049 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
2020-04-16 11:24:02,274 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
2020-04-16 11:35:47,168 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
2020-04-16 11:45:54,517 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
2020-04-16 11:47:50,095 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
2020-04-16 11:50:03,316 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
2020-04-16 11:51:16,235 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
2020-04-16 11:53:04,785 INFO: Microblog startup [in D:\Flask\my_project\app\__init__.py:55]
